const mongoose = require('mongoose');
const Question = require('./models/Question');
const CurrentAffairs = require('./models/CurrentAffairs');
const StudyMaterial = require('./models/StudyMaterial');
const questions = [
  { question: "Which Article of the Indian Constitution provides for the appointment of the Chief Justice of India?", options: ["Article 124", "Article 126", "Article 128", "Article 148"], correctAnswer: 0, explanation: "Article 124 of the Constitution provides for the appointment of the Chief Justice of India. The President appoints the CJI after consultation with such judges as the President deems necessary.", subject: "Polity", topic: "Constitution", difficulty: "Medium" },
  { question: "The 'Great Dying' refers to:", options: ["Black Death in Europe", "Plague of Justinian", "Columbian Exchange diseases", "Antonine Plague"], correctAnswer: 2, explanation: "The 'Great Dying' refers to the devastating epidemic that swept through the Americas after European contact, killing 90-95% of the indigenous population due to diseases like smallpox.", subject: "History", topic: "Modern", difficulty: "Medium" },
  { question: "Which of the following is NOT a part of the Himalayan mountain range?", options: ["Zanskar", "Karakoram", "Aravalli", "Kangchenjunga"], correctAnswer: 2, explanation: "Aravalli is the oldest mountain range in India, located in northwestern India. It is not part of the Himalayas.", subject: "Geography", topic: "Physical", difficulty: "Easy" },
  { question: "The Self-Help Group (SHG) model in India is associated with:", options: ["Rural development", "Urban housing", "Industrial development", "Educational reform"], correctAnswer: 0, explanation: "SHGs are informal groups of 10-20 people who come together to address their common issues. They are primarily used for rural development and women empowerment.", subject: "Economy", topic: "Poverty", difficulty: "Easy" },
  { question: "Which satellite system is India's regional navigation system?", options: ["GPS", "GLONASS", "NavIC", "Galileo"], correctAnswer: 2, explanation: "NavIC (Navigation with Indian Constellation) is India's regional navigation satellite system, operational since 2016.", subject: "Science", topic: "Space", difficulty: "Medium" },
  { question: "The 'Environment Impact Assessment' (EIA) in India is regulated under:", options: ["Air Act", "Water Act", "Environment Protection Act", "Wildlife Act"], correctAnswer: 2, explanation: "The Environment (Protection) Act, 1986 provides the legal framework for Environmental Impact Assessment in India.", subject: "Environment", topic: "Policies", difficulty: "Medium" },
  { question: "Who among the following wrote 'Discovery of India'?", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "B.R. Ambedkar", "Rabindranath Tagore"], correctAnswer: 0, explanation: "Jawaharlal Nehru wrote 'Discovery of India' in 1946 during his imprisonment in Ahmednagar Fort.", subject: "History", topic: "Modern", difficulty: "Easy" },
  { question: "Which state has the longest coastline in India?", options: ["Gujarat", "Maharashtra", "Tamil Nadu", "Andhra Pradesh"], correctAnswer: 0, explanation: "Gujarat has the longest coastline in India, stretching about 1,600 km along the Arabian Sea.", subject: "Geography", topic: "India", difficulty: "Easy" },
  { question: "The Fifth Schedule of the Constitution deals with:", options: ["Scheduled Tribes", "Scheduled Castes", "Union Territories", "Languages"], correctAnswer: 0, explanation: "The Fifth Schedule deals with the administration and control of Scheduled Areas and Scheduled Tribes in states other than Assam, Nagaland, and other northeastern states.", subject: "Polity", topic: "Constitution", difficulty: "Hard" },
  { question: "What is the full form of NITI Aayog?", options: ["National Institution for Transforming India", "National Initiative for Technical Integration", "National Investment and Trade Initiative", "National Institute of Technology and Innovation"], correctAnswer: 0, explanation: "NITI Aayog stands for National Institution for Transforming India. It was established in 2015 replacing the Planning Commission.", subject: "Economy", topic: "Planning", difficulty: "Easy" },
  { question: "The Kharif cropping season is:", options: ["October to March", "April to September", "June to November", "March to June"], correctAnswer: 1, explanation: "Kharif season is from June to November (April to September in some parts), coinciding with the monsoon season.", subject: "Geography", topic: "Agriculture", difficulty: "Easy" },
  { question: "Which Article empowers the President to declare emergency?", options: ["Article 352", "Article 356", "Article 360", "Article 368"], correctAnswer: 0, explanation: "Article 352 deals with National Emergency due to war, armed rebellion, or external aggression. It can be declared by the President.", subject: "Polity", topic: "Emergency", difficulty: "Medium" },
  { question: "The 'Battle of Plassey' was fought in:", options: ["1757", "1764", "1857", "1947"], correctAnswer: 0, explanation: "The Battle of Plassey was fought on June 23, 1757 between the British East India Company and the Nawab of Bengal and his French allies.", subject: "History", topic: "Modern", difficulty: "Easy" },
  { question: "Which gas is most abundant in the Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctAnswer: 2, explanation: "Nitrogen makes up about 78% of the Earth's atmosphere, followed by Oxygen at 21% and Argon at 0.93%.", subject: "Science", topic: "Environment", difficulty: "Easy" },
  { question: "The concept of 'Basic Structure' of the Constitution was introduced by:", options: ["Supreme Court", "Parliament", "President", "Election Commission"], correctAnswer: 0, explanation: "The 'Basic Structure' doctrine was evolved by the Supreme Court in the Kesavananda Bharti case (1973).", subject: "Polity", topic: "Constitution", difficulty: "Medium" },
  { question: "Which river is known as 'Ganga of South'?", options: ["Krishna", "Godavari", "Kaveri", "Narmada"], correctAnswer: 1, explanation: "The Godavari is often called the 'Ganga of South' as it is the largest river in peninsular India.", subject: "Geography", topic: "Rivers", difficulty: "Easy" },
  { question: "The Quit India Movement was launched in:", options: ["1940", "1942", "1944", "1946"], correctAnswer: 1, explanation: "The Quit India Movement was launched by Mahatma Gandhi on August 8, 1942, demanding an end to British rule in India.", subject: "History", topic: "Independence", difficulty: "Easy" },
  { question: "Which organ of the UN is responsible for appointing judges to the International Court of Justice?", options: ["General Assembly", "Security Council", "Both A and B", "Neither A nor B"], correctAnswer: 2, explanation: "Both the General Assembly and the Security Council elect judges to the ICJ. A candidate needs a two-thirds majority in GA and any majority in SC.", subject: "Polity", topic: "International", difficulty: "Hard" },
  { question: "What is India's rank in the Global Innovation Index 2023?", options: ["40th", "50th", "45th", "55th"], correctAnswer: 0, explanation: "India ranked 40th in the Global Innovation Index 2023, showing improvement from previous years.", subject: "Economy", topic: "Innovation", difficulty: "Medium" },
  { question: "The 'East India Company' was established in:", options: ["1600", "1605", "1610", "1620"], correctAnswer: 0, explanation: "The East India Company was established on December 31, 1600, by Queen Elizabeth I.", subject: "History", topic: "Modern", difficulty: "Easy" },
  { question: "Which ministry implements the PM-KISAN scheme?", options: ["Ministry of Agriculture", "Ministry of Rural Development", "Ministry of Finance", "Ministry of Food Processing"], correctAnswer: 0, explanation: "PM-KISAN is implemented by the Ministry of Agriculture & Farmers Welfare. It provides income support of Rs 6000 per year to farmer families.", subject: "Economy", topic: "Schemes", difficulty: "Medium" },
  { question: "The National Green Tribunal was established in:", options: ["2008", "2010", "2012", "2014"], correctAnswer: 1, explanation: "The National Green Tribunal was established in 2010 under the National Green Tribunal Act, 2010.", subject: "Environment", topic: "Institutions", difficulty: "Medium" },
];
const affairs = [
  { title: "India Launches Chandrayaan-3 Moon Mission", content: "ISRO successfully launched Chandrayaan-3, India's third lunar exploration mission. The mission aims to demonstrate safe landing and roving capabilities on the Moon. It consists of lander Vikram and rover Pragyan. The mission achieved historic success by landing near the Moon's south pole.", summary: "India's third moon mission successfully launched", date: new Date(), category: "Science & Tech", tags: ["Space", "ISRO", "Moon"], importance: "High" },
  { title: "UPSC Releases 2024 Exam Calendar", content: "The Union Public Service Commission has released the examination calendar for 2024. The Preliminary exam is scheduled for June 2024, followed by Mains in September 2024.", summary: "UPSC announces exam dates for 2024", date: new Date(), category: "National", tags: ["UPSC", "Exam"], importance: "High" },
  { title: "Parliament Passes Digital Personal Data Protection Act", content: "Parliament passes the Digital Personal Data Protection Act, 2023 to protect personal data and establish a data protection board in India. The Act defines obligations for data processors and rights of data principals.", summary: "New data protection law passed", date: new Date(), category: "National", tags: ["Law", "Data", "Privacy"], importance: "High" },
  { title: "India Signs G20 Leaders' Declaration", content: "India successfully led the G20 summit and got unanimous agreement on various key issues including climate change, digital economy, and sustainable development. India proposed the Global Biofuels Alliance and Mishra Commission.", summary: "India leads successful G20 summit", date: new Date(), category: "International", tags: ["G20", "India", "Summit"], importance: "High" },
  { title: "RBI Keeps Repo Rate Unchanged", content: "Reserve Bank of India maintains repo rate at 6.5% citing inflation concerns while supporting growth momentum in the economy. RBI also announced India's GDP growth forecast at 6.5% for FY24.", summary: "RBI keeps interest rates steady", date: new Date(), category: "Economy", tags: ["RBI", "Finance", "Economy"], importance: "Medium" },
  { title: "PM Modi Launches Ayushman Bharat Health IDs", content: "Prime Minister launched the Ayushman Bharat Health ID scheme providing digital health IDs to citizens. This will enable seamless sharing of medical records across healthcare providers.", summary: "Digital health IDs launched", date: new Date(), category: "National", tags: ["Health", "PM Modi", "Schemes"], importance: "High" },
  { title: "India Achieves 100 GW Renewable Energy Target", content: "India achieved its target of 100 GW renewable energy capacity ahead of schedule. The country now aims for 500 GW non-fossil capacity by 2030 as part of climate commitments.", summary: "India reaches 100 GW renewable target", date: new Date(), category: "Environment", tags: ["Energy", "Climate", "Renewable"], importance: "High" },
  { title: "ISRO Successfully Tests Reusable Launch Vehicle", content: "ISRO successfully conducted a landing test of its Reusable Launch Vehicle (RLV). This technology can significantly reduce the cost of space missions by allowing repeated use of rockets.", summary: "RLV technology test successful", date: new Date(), category: "Science & Tech", tags: ["Space", "ISRO", "Technology"], importance: "Medium" },
];
const materials = [
  // HISTORY - Ancient
  { title: "Indus Valley Civilization", content: "The Indus Valley Civilization (3300-1300 BCE) was one of the world's earliest urban civilizations. Major cities: Harappa, Mohenjo-daro, Dholavira, Rakhigarhi. Key features: Town planning, drainage system, weighing & measuring systems, script (undecoded). Artifacts: Bronze toys, terracotta seals, gold jewelry. Decline theories: Climate change, river course shift, Aryan invasion.", subject: "History", topic: "Ancient", type: "Notes", importantPoints: ["Period: 3300-1300 BCE", "Cities: Harappa, Mohenjo-daro", "Script: Undecoded", "Decline: 1900 BCE"] },
  { title: "Vedic Period", content: "The Vedic Period (1500-500 BCE) saw composition of Vedas. Early Vedic: Rig, Sama, Yajur, Atharva Vedas. Later Vedic: 16 Mahajanapadas, Rise of Buddhism & Jainism. Social structure: Varna system (Brahmins, Kshatriyas, Vaishyas, Shudras). Philosophy: Karma, Dharma, Moksha.", subject: "History", topic: "Ancient", type: "Notes", importantPoints: ["Vedas: Rig, Sama, Yajur, Atharva", "16 Mahajanapadas", "Buddhism & Jainism rise", "Varna system"] },
  { title: "Maurya Empire", content: "Maurya Empire (322-185 BCE) founded by Chandragupta Maurya. Key rulers: Chandragupta (defeated Seleucus), Bindusara, Ashoka (Kalinga war, Dhamma). Administration: Centralized bureaucracy, spy system, maintained army. Ashoka's inscriptions: Rock Edicts, Pillar Edicts. Decline: Weak successors, invasions.", subject: "History", topic: "Ancient", type: "Notes", importantPoints: ["Founder: Chandragupta Maurya", "Ashoka's Kalinga War", "Dhamma propagation", "Decline: 185 BCE"] },
  { title: "Gupta Period - Golden Age", content: "Gupta Period (320-550 CE) called India's Golden Age. Achievements: Kalidasa (Abhijnanasakuntalam), Aryabhata (Zero, Pi), Varahamihira (Astronomy). Art: Ajanta Caves, Sanchi Stupa. Trade & commerce flourishing. Feudalism began. Invaders: White Huns ended Gupta empire.", subject: "History", topic: "Ancient", type: "Notes", importantPoints: ["Golden Age of India", "Kalidasa's works", "Aryabhata's inventions", "Decline: White Huns"] },
  
  // HISTORY - Medieval
  { title: "Delhi Sultanate", content: "Delhi Sultanate (1206-1526): Slave Dynasty (Qutb-ud-din Aibak), Khilji (Alauddin Khalji - market reforms), Tughlaq (Muhammad bin Tughlaq - token currency failure), Sayyid & Lodi dynasties. Important rulers: Iltutmish (delegate system), Firuz Tughlaq (canals, hospitals).", subject: "History", topic: "Medieval", type: "Notes", importantPoints: ["1206-1526 CE", "Five dynasties", "Alauddin Khalji reforms", "Muhammad bin Tughlaq"] },
  { title: "Vijayanagara Empire", content: "Vijayanagara Empire (1336-1646) founded by Harihara I & Bukka Raya. Famous rulers: Krishna Deva Raya (Abhinav Kalidasa). Features: Hampi capital, irrigation systems (tanks, wells), flourishing trade. Battle of Talikota (1565) led to decline. Contributions: Literature, art, architecture.", subject: "History", topic: "Medieval", type: "Notes", importantPoints: ["1336-1646 CE", "Capital: Hampi", "Krishna Deva Raya", "Battle of Talikota"] },
  { title: "Mughal Empire", content: "Mughal Empire (1526-1857): Babur (First battle of Panipat), Humayun, Akbar (Din-i-Ilahi, Mansabdari), Shah Jahan (Taj Mahal), Aurangzeb (Religious policies). Administration: Centralized, Mansabdari system, Revenue (Zabt). Art & Architecture: Miniature painting, Taj Mahal, Red Fort.", subject: "History", topic: "Medieval", type: "Notes", importantPoints: ["1526-1857 CE", "Mansabdari system", "Akbars religious policy", "Taj Mahal"] },
  
  // HISTORY - Modern
  { title: "British East India Company", content: "East India Company (1600-1858) established by Queen Elizabeth I. Battle of Plassey (1757) - Robert Clive. Battle of Buxar (1764). Permanent Settlement (1793) - Lord Cornwallis. Revenue systems: Permanent, Ryotwari, Mahalwari. 1857 Rebellion led to end of Company rule.", subject: "History", topic: "Modern", type: "Notes", importantPoints: ["1600: Company founded", "1757: Plassey", "1857: First War of Independence"] },
  { title: "Indian National Congress", content: "INC founded (1885) by A.O. Hume. Sessions: Bombay (1905), Calcutta (1906 - Swadeshi), Lucknow (1916 - Home Rule). Leaders: Gandhi, Nehru, Bose, Patel. Methods: Swadeshi, Satyagraha, Non-cooperation, Civil Disobedience. Partition (1947) - Mountbatten Plan.", subject: "History", topic: "Modern", type: "Notes", importantPoints: ["1885: INC founded", "Gandhi's movements", "1947: Independence"] },
  
  // GEOGRAPHY
  { title: "Physical Geography of India", content: "India: 3,287,263 sq km, 7th largest. Mountains: Himalayas (Karakoram, Zanskar, Ladakh), Purva (Vindhyas, Satpuras), CENO (Shillong). Plains: Indo-Gangetic (Alluvial soil), Coastal (Arabian Sea, Bay of Bengal), Islands (Andaman, Lakshadweep). Rivers: Himalayan (Ganga, Yamuna, Indus), Peninsular (Godavari, Krishna, Mahanadi).", subject: "Geography", topic: "Physical", type: "Notes", importantPoints: ["Area: 3.29 million sq km", "Himalayas: 2500 km", "Indo-Gangetic plain", "Peninsular rivers"] },
  { title: "Indian Monsoon", content: "Monsoon: Southwest (June-Sept), Northeast (Oct-Nov). Jet stream: Easterly (summer), Westerly (winter). ITCZ: Inter Tropical Convergence Zone. Features: Onset (Kerala - June 1), Withdrawal (Rajasthan - October). Rainfall: Western Ghats (heavy), Thar Desert (less). El Nino impact: Weak monsoon.", subject: "Geography", topic: "Climate", type: "Notes", importantPoints: ["SW Monsoon: June-Sept", "Onset: Kerala June 1", "Western Ghats: High rainfall", "El Nino effect"] },
  { title: "Rivers of India", content: "Himalayan Rivers: Indus (Srinagar), Ganga (Allahabad), Brahmaputra (Tezpur). Peninsular: Godavari (Rajahmundry), Krishna (Vijayawada), Mahanadi (Cuttack), Narmada (Bharuch), Tapti (Surat). Multi-purpose: Bhakra Nangal, Hirakud, Nagarjuna Sagar.", subject: "Geography", topic: "Rivers", type: "Notes", importantPoints: ["Ganga: 2525 km", "Godavari: 1465 km", "Brahmaputra:跨境", "Narmada: 1312 km"] },
  { title: "Climate Zones of India", content: "Climate types: Tropical Wet (Kerala - monsoonal), Dry (Thar Desert - hot arid), Subtropical (North - humid), Mountain (Himalayas - tundra). Koppen classification: Am (Monsoon), Aw (Tropical savanna), BSh (Semi-arid), Cwg (Humid subtropical).", subject: "Geography", topic: "Climate", type: "Quick Review", importantPoints: ["Tropical monsoon", "Subtropical humid", "Mountain tundra", "Desert arid"] },
  
  // POLITY
  { title: "Indian Constitution - Features", content: "Constitution: Lengthiest (Original: 395 articles, 22 parts, 8 schedules; Now: 448 articles). Features: Sovereign, Socialist, Secular, Democratic, Republic; Parliamentary; Single citizenship; Fundamental Rights (6); Directive Principles; Emergency provisions (352, 356, 360).", subject: "Polity", topic: "Constitution", type: "Notes", importantPoints: ["Sovereign, Socialist, Secular", "FRs: 6 rights", "DPSP: Non-justiciable", "Emergency: 3 types"] },
  { title: "Parliament of India", content: "Parliament: President (Nominal head), Lok Sabha (543 elected - 5 yrs), Rajya Sabha (250 max - 6 yrs, 1/3 rotation). Functions: Lawmaking, Control, Representation. Sessions: Budget (Feb-May), Monsoon (July-Sep), Winter (Nov-Jan). Parliamentary committees: Public Accounts, Estimates, Standing.", subject: "Polity", topic: "Legislature", type: "Notes", importantPoints: ["Lok Sabha: 543 seats", "Rajya Sabha: 250 max", "President: Nominal head", "Committees: Important"] },
  { title: "President of India", content: "President: Indirect election (Electoral College). Term: 5 years. Powers: Executive (appointments), Legislative (summons, assent), Judicial (pardon). Emergency: Article 352 (National), 356 (President's Rule), 360 (Financial). Veto: Pocket, Absolute, Qualified.", subject: "Polity", topic: "Executive", type: "Notes", importantPoints: ["Indirect election", "Emergency powers", "Veto options", "Article 356: President Rule"] },
  { title: "Supreme Court", content: "Supreme Court: Chief Justice (appointed by President), 33 judges (maximum). Jurisdiction: Original (Disputes states), Appellate (Constitutional), Advisory (Article 143). Powers: Judicial Review, Fundamental Rights, Constitutional interpretation. Basic Structure doctrine (1973).", subject: "Polity", topic: "Judiciary", type: "Notes", importantPoints: ["Chief Justice appointment", "Judicial Review", "Basic Structure", "Article 32: HR enforcement"] },
  
  // ECONOMY
  { title: "Indian Economy Overview", content: "Economy: 5th largest (GDP $3.7 trillion). Sectors: Agriculture (17%), Industry (25%), Services (57%). GDP growth: 7% (2023-24). NITI Aayog: replaces Planning Commission (2015). MSP: Minimum Support Price. PMI: Manufacturing (50+). RBI: Monetary policy.", subject: "Economy", topic: "General", type: "Notes", importantPoints: ["5th largest economy", "Services: 57%", "NITI Aayog 2015", "RBI: Repo rate"] },
  { title: "Five Year Plans", content: "Planning: First Plan (1951-56) - Agriculture, Last Plan (2012-17). NITI Aayog: 3-year Action Plan, 7-year Vision, 15-year Strategy. Goals: Growth, Poverty reduction, Employment. Sectors: Agriculture, Industry, Services, Infrastructure.失败了: Resource constraint.", subject: "Economy", topic: "Planning", type: "Notes", importantPoints: ["1951-2017: 12 Plans", "NITI Aayog replaces", "Objectives: Growth, Jobs", "Sector priorities"] },
  { title: "Poverty & Unemployment", content: "Poverty: Multidimensional Poverty Index (MPI). Sectors: Rural, Urban. Schemes: PM-JAN (2018), PM-G (2006), MGNREGA (2005). Unemployment: 4.8% (2023). Types: Frictional, Structural, Cyclical. Schemes: PMKVY (2015), Skill India.", subject: "Economy", topic: "Poverty", type: "Notes", importantPoints: ["MPI for poverty", "MGNREGA: 100 days", "Unemployment: 4.8%", "Skill India mission"] },
  
  // SCIENCE
  { title: "Space Technology", content: "ISRO: Founded 1969. Missions: Chandrayaan (Moon), Mangalyaan (Mars), Gaganyaan (Human spaceflight). Satellites: INSAT (communication), IRS (remote sensing), NAVIC (navigation). Launch vehicles: PSLV, GSLV, LVM3. Achievements: 100+ missions, Mars in first attempt.", subject: "Science", topic: "Space", type: "Notes", importantPoints: ["ISRO: 1969", "Chandrayaan-3: 2023", "Mars: First attempt", "PSLV: Reliable"] },
  { title: "Nuclear & Defense", content: "Nuclear: BARC (1954), Pokhran tests (1974, 1998). Defense: DRDO, HAL, Ordnance factories. Missiles: Prithvi (surface), Agni (ballistic), Brahmos (cruise). Forces: Army, Navy, Air Force. Aircraft: Tejas, Rafale.", subject: "Science", topic: "Technology", type: "Notes", importantPoints: ["Nuclear: BARC, Pokhran", "Missiles: Agni series", "Tejas: Indigenous", "DRDO: R&D"] },
  { title: "IT & Communication", content: "IT: Software exports $200+ billion. Companies: TCS, Infosy, Wipro. Digital India: 2015. 5G rollout: 2022. BHIM app, UPI. Startup India: 2016. Unicorns: 100+. AI, ML, Blockchain growth.", subject: "Science", topic: "Technology", type: "Quick Review", importantPoints: ["IT exports: $200B", "Digital India 2015", "UPI: 5B transactions", "100+ unicorns"] },
  
  // ENVIRONMENT
  { title: "Biodiversity & Wildlife", content: "Biodiversity: 8% species (world). Hotspots: Western Ghats, Himalayas. National Parks: 106, Wildlife Sanctuaries: 564. Project Tiger (1973), Project Elephant (1991). Endangered: Tiger, Rhino, Elephant. CITES, IUCN. Red List.", subject: "Environment", topic: "Wildlife", type: "Notes", importantPoints: ["8% world species", "Project Tiger", "Endangered: Tiger, Rhino", "Red List"] },
  { title: "Climate Change & Paris Agreement", content: "Paris Agreement (2015): 1.5°C target. NDC: Net Zero by 2070. Carbon market. India: Renewable energy (500 GW by 2030), National Adaptation Fund. UNFCCC: Framework Convention 1992, Kyoto Protocol 1997, Paris 2015.", subject: "Environment", topic: "Climate", type: "Notes", importantPoints: ["Paris: 1.5°C target", "Net Zero: 2070", "500 GW renewable", "UNFCCC"] },
  { title: "Disaster Management", content: "Disasters: Floods (Bihar, Assam), Earthquakes (Gujarat 2001, Nepal 2015), Cyclones (Odisha, Tamil Nadu), Landslides (Himalayas). NDMA: 2006. Schemes: SDRF, DM Act 2005. Early warning systems. Response: NDRF.", subject: "Environment", topic: "Disaster", type: "Notes", importantPoints: ["NDMA: 2006", "NDRF teams", "DM Act 2005", "Early warning"] },
  
  // ETHICS
  { title: "Ethics - Concept & Applications", content: "Ethics: Study of moral principles. Key concepts: Integrity (honesty, consistency), Accountability (responsibility), Public Service (public interest). Case studies: Bhopal gas, Nestle milk, Satyendra Dubey. Values: Empathy, Compassion, Patriotism.", subject: "Ethics", topic: "Concept", type: "Notes", importantPoints: ["Integrity matters", "Accountability", "Case study approach", "Values: empathy, compassion"] },
  { title: "Emotional Intelligence", content: "EQ: Self-awareness, Self-regulation, Motivation, Empathy, Social skills. Difference from IQ. Applications: Leadership, Conflict resolution, Decision making. Emotional quotient training. Corporate governance.", subject: "Ethics", topic: "Concept", type: "Notes", importantPoints: ["5 components of EQ", "EQ vs IQ", "Leadership skills", "Conflict resolution"] },
];
mongoose.connect('mongodb://localhost:27017/upscprep', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('Connected to MongoDB');
    await Question.deleteMany({});
    await CurrentAffairs.deleteMany({});
    await StudyMaterial.deleteMany({});
    
    await Question.insertMany(questions);
    await CurrentAffairs.insertMany(affairs);
    await StudyMaterial.insertMany(materials);
    
    console.log('Data seeded successfully!');
    console.log(`Questions: ${questions.length}`);
    console.log(`Current Affairs: ${affairs.length}`);
    console.log(`Study Materials: ${materials.length}`);
    process.exit();
     }).catch(err => console.log(err));